import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/Header'
import { useCallback, useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [foo, setFoo] = useState(1)
  const [text, setText] = useState("")
  const [isShow, setisShow] = useState(true)


  const handleClick = useCallback((e) => {
    if(foo<10){
      setFoo(foo => foo+1)
    }
  }, [foo])

  useEffect(() => {
    document.body.style.backgroundColor ="purple";
    return()=>{
      document.body.style.backgroundColor ="";
    }
  }, [foo]);

  const handleDisplay = useCallback(() => {
    setisShow((isShow) => !isShow)
  },[])
 
  console.log(text)

  const handleChange = useCallback((e) => {
    if(e.target.value.length > 5){
      alert("5文字以内にしてください")
      return
    }
    setText(e.target.value.trim())
  },[])

  return (
    <>
      <Head>
        <title>index pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isShow ? <h1>{foo}</h1> : null}
      <button onClick={handleClick}>ボタン</button> 
      <button
        onClick={handleDisplay}
        >
          {isShow ? "非表示" : "表示"}</button>
      <input type="text" value={text} onChange={handleChange}  />
      <Main title="Index Page" page="index" />
      <Footer />
    </>
  )
}
