import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/Header'
import { useCallback, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const foo = 1;

   const handleClick = useCallback((e) => {
     console.log(e.target.href);
     e.preventDefault();
     alert(foo);
   },[])
   
  useEffect(() => {
    console.log("マウント時");
    document.body.style.backgroundColor ="purple";
    return()=>{
      console.log("アンマウント時");
      document.body.style.backgroundColor ="";
    }
  },[]);

  return (
    <>
      <Head>
        <title>index pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/<a href="/about" onClick={handleClick}>
        ボタン
      </a> }
      <Main title="Index Page" page="index" />
      <Footer />
    </>
  )
}
