import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Links } from '@/components/Links'
import styles from '@/styles/Home.module.css'
import { Footer } from '@/components/Footer'
import {Headline} from '@/components/Headline'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>index pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Headline  title="Index Page" page="index" />
        <Links />
      </main>
      <Footer />
    </>
  )
}
